### ISSUE TITLE
Ajouter contours administratif Nouvelle Calédonie

### ISSUE THREAD

**Issue by vinsag** [etalab/contours-administratifs#21]
Les contours de la Nouvelle Calédonie ne sont actuellement pas présent.
Il faudrait les intégrer grace au site officiel : https://georep.nc/
Pour les limites administratives : https://georep-dtsi-sgt.opendata.arcgis.com/pages/limites-administratives
Pouvez vous les intégrer et effectuer un nouvel export s'il vous plait ?

**Comment by ThomasG77** [comment]
Les contours sont présents mais ils proviennent d'OpenStreetMap pour le moment.

Vérifiable via

    ogrinfo -so -ro /vsicurl/http://etalab-datasets.geo.data.gouv.fr/contours-administratifs/2022/geojson/communes-5m.geojson -dialect SQLite -sql "SELECT * FROM \"communes-5m\" WHERE \"collectiviteOutremer\" = '988'"
