### ISSUE TITLE
Contours de collectivités d'outremer (COM)

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/contours-administratifs#23]
Si les communes des collectivités d'outremer sont bien exportées dans la couche `communes` des fichiers GeoJSON, mais aussi dans les tuiles vectorielles, les contours de ces collectivités ne sont pas disponibles.

Nous avons déjà discuté de ce point, je le documente simplement pour pouvoir lier des issues.

Scénario 1 : proposer une couche `collectivites-outremer`
Scnéario 2 : assimuler les collectivités d'outremer à des `departements` et `regions`

**Comment by ThomasG77** [comment]
Pris l'option du scénario 2
Effectué au niveau de contours ainsi que dans l'API Découpage Administratif.
Je ferme
